package ims;

import java.awt.Font;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

public class MEmployee extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement insert1 = null;
    Statement search1 = null;
    PreparedStatement search = null;
    ResultSet rs = null;
    
    
    public MEmployee() throws ClassNotFoundException, SQLException {
        initComponents();
        con = DBConnection.connectdb();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        try {
            result();
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "No record found");
        }
        
        jTable1.getTableHeader().setFont(new Font("Segoe", Font.ITALIC, 16));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        img_path = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Luid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        igender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Lname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Lemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Taddress = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        Ddob = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Lcontact = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Ddoj = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        Iusertype = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        Lsalary = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Lpass = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1392, 801));

        jPanel5.setBackground(new java.awt.Color(231, 234, 244));

        jPanel7.setBackground(new java.awt.Color(231, 234, 244));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel7.setMaximumSize(new java.awt.Dimension(1131, 445));
        jPanel7.setMinimumSize(new java.awt.Dimension(1131, 445));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));

        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Upload");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDesktopPane1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(img_path, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(img_path)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Unique Id");

        Luid.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Luid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel5.setText("Gender");
        jLabel5.setMaximumSize(new java.awt.Dimension(68, 22));
        jLabel5.setMinimumSize(new java.awt.Dimension(68, 22));
        jLabel5.setPreferredSize(new java.awt.Dimension(68, 22));

        igender.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        igender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Other" }));
        igender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        igender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igenderActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel6.setText("Name");
        jLabel6.setPreferredSize(new java.awt.Dimension(68, 22));

        Lname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel7.setText("Email");

        Lemail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Lemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel8.setText("Address");

        Taddress.setColumns(20);
        Taddress.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Taddress.setRows(5);
        Taddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(Taddress);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("D.O.B");

        Ddob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Ddob.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Password");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Contact No.");

        Lcontact.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Lcontact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("D.O.J");

        Ddoj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Ddoj.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("User Type");

        Iusertype.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Iusertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Employee" }));
        Iusertype.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Salary");

        Lsalary.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Lsalary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMaximumSize(new java.awt.Dimension(47, 28));
        jButton1.setMinimumSize(new java.awt.Dimension(47, 28));
        jButton1.setPreferredSize(new java.awt.Dimension(47, 28));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setMaximumSize(new java.awt.Dimension(47, 28));
        jButton2.setMinimumSize(new java.awt.Dimension(47, 28));
        jButton2.setPreferredSize(new java.awt.Dimension(47, 28));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setMaximumSize(new java.awt.Dimension(47, 28));
        jButton3.setMinimumSize(new java.awt.Dimension(47, 28));
        jButton3.setPreferredSize(new java.awt.Dimension(47, 28));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Update");
        jButton5.setBorder(null);
        jButton5.setMaximumSize(new java.awt.Dimension(47, 28));
        jButton5.setMinimumSize(new java.awt.Dimension(47, 28));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Clear");
        jButton6.setBorder(null);
        jButton6.setMaximumSize(new java.awt.Dimension(47, 28));
        jButton6.setMinimumSize(new java.awt.Dimension(47, 28));
        jButton6.setPreferredSize(new java.awt.Dimension(47, 28));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Lpass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Lpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Luid, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(Lname))
                                    .addComponent(Lemail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Ddob, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(igender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lpass))))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ddoj, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Iusertype, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Luid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(igender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Lname)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ddoj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ddob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                .addComponent(Lemail)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Iusertype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Lpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Lsalary)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        jPanel1.setBackground(new java.awt.Color(231, 234, 244));
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 161));

        jScrollPane2.setBackground(new java.awt.Color(231, 234, 244));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane2.setPreferredSize(jTable1.getPreferredSize());

        jTable1.setBackground(new java.awt.Color(231, 234, 244));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Unique ID", "UserType", "Name", "Gender", "Contact", "DOB", "DOJ", "Email", "Password", "Address", "Salary"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(22);
        jTable1.setSelectionBackground(new java.awt.Color(43, 62, 79));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        jPanel3.setBackground(new java.awt.Color(231, 234, 244));

        jLabel1.setBackground(new java.awt.Color(43, 62, 79));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Employee Details");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1278, Short.MAX_VALUE)
                .addGap(223, 223, 223))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser img = new JFileChooser();
        img.showSaveDialog(null);
        File file = img.getSelectedFile();
        ImageIcon im = new ImageIcon(file.toString());
        Image imm = im.getImage();
        Image imgscale = imm.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg = new ImageIcon(imgscale);
        jLabel3.setIcon(scaledimg);
        filename = file.getAbsolutePath();
        img_path.setText(filename);

        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bass = new ByteArrayOutputStream();
            byte[] a = new byte[1024];
            for (int readNum; (readNum=fis.read(a))!=-1;) {
                bass.write(a, 0, readNum);
            }

            photo=bass.toByteArray();
        }
        catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void igenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_igenderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(Luid.getText().isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please Search By ID");
        }
        else {
            String sql1 = "SELECT * FROM Emp_Ims WHERE ID = '"+Luid.getText()+"'";

            try {
                search1 = con.createStatement();
                rs = search1.executeQuery(sql1);
                rs.next();
                Luid.setEditable(false);
                Lname.setText(rs.getString(3));
                Lcontact.setText(rs.getString(5));
                Lemail.setText(rs.getString(8));
                Lpass.setText(rs.getString(9));
                Taddress.setText(rs.getString(10));
                Lsalary.setText(rs.getString(11));

                try {
                    search1 = con.createStatement();
                    rs = search1.executeQuery("SELECT * FROM EMP_IMS WHERE ID = '"+Luid.getText()+"'");
                    rs.next();
                    byte[] img = rs.getBytes(12);
                    ImageIcon imm = new ImageIcon(img);
                    Image im = imm.getImage();
                    Image myimg = im.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon newimg = new ImageIcon(myimg);
                    jLabel3.setIcon(newimg);
                }
                catch(Exception e) {

                }

            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(null, ex);
            }

            java.util.Date dob1;
            java.util.Date doj1;
            try {
                dob1 = new SimpleDateFormat("yyyy-MM-dd").parse((String)rs.getDate(6).toString());
                doj1 = new SimpleDateFormat("yyyy-MM-dd").parse((String)rs.getDate(7).toString());
                Ddob.setDate(dob1);
                Ddoj.setDate(doj1);
            } catch (SQLException ex) {
                Logger.getLogger(MEmployee.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(MEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }

            try{
                if(rs.getString(4).equals("Male")) {
                    igender.setSelectedIndex(1);
                }
                else if (rs.getString(4).equals("Female")){
                    igender.setSelectedIndex(2);
                }
                else {
                    igender.setSelectedIndex(3);
                }

                if(rs.getString(2).equals("Admin")) {
                    Iusertype.setSelectedIndex(1);
                }
                else {
                    Iusertype.setSelectedIndex(2);
                }
            }
            catch(Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(null, "");
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(Luid.getText().isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please Enter Unique ID");
        }
        else if (Lname.getText().isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please Enter the Name");
        }
        else if (Lemail.getText().isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter the Email");
        }
        else if (Taddress.getText().isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter the Address");
        }
        else if (((JTextField)Ddob.getDateEditor().getUiComponent()).getText().isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter the Date of Birth");
        }
        else if (((JTextField)Ddoj.getDateEditor().getUiComponent()).getText().isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter the Date of Joining");
        }
        else if (Lpass.getText().isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please Set The Password");
        }
        else if (Lcontact.getText().isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter Contact No.");
        }
        else {
            String sql = "INSERT INTO EMP_IMS(id,usertype,name,gender,contact,dob,doj,email,password,address,salary,image) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";

            try {
                insert1 = con.prepareStatement(sql);
                insert1.setString(1, Luid.getText());
                insert1.setString(2, Iusertype.getItemAt(Iusertype.getSelectedIndex()));
                insert1.setString(3, Lname.getText());
                insert1.setString(4, igender.getItemAt(igender.getSelectedIndex()));
                insert1.setString(5, Lcontact.getText());
                insert1.setString(6, ((JTextField)Ddob.getDateEditor().getUiComponent()).getText());
                insert1.setString(7, ((JTextField)Ddoj.getDateEditor().getUiComponent()).getText());
                insert1.setString(8, Lemail.getText());
                insert1.setString(9, Lpass.getText());
                insert1.setString(10, Taddress.getText());
                insert1.setString(11, Lsalary.getText());
                insert1.setBytes(12, photo);
                insert1.execute();
                javax.swing.JOptionPane.showMessageDialog(null, "Registered Successfully");
                result();
                clear();

            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(Luid.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please Enter Unique ID");
        }
        else {
            String sql4 = "DELETE FROM EMP_IMS WHERE ID = '"+Luid.getText()+"'";

            try {
                insert1 = con.prepareStatement(sql4);
                insert1.execute();
                javax.swing.JOptionPane.showMessageDialog(null, "Deleted Successfully");
                result();
                clear();

            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(Luid.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please Enter Unique ID");
        }
        else {
            if (Lname.getText().isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please Enter the Name");
            }
            else if (Lemail.getText().isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please enter the Email");
            }
            else if (Taddress.getText().isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please enter the Address");
            }
            else if (((JTextField)Ddob.getDateEditor().getUiComponent()).getText().isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please enter the Date of Birth");
            }
            else if (((JTextField)Ddoj.getDateEditor().getUiComponent()).getText().isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please enter the Date of Joining");
            }
            else if (Lpass.getText().isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please Set The Password");
            }
            else if (Lcontact.getText().isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please enter Contact No.");
            }
            else {
                String sql2 = "UPDATE EMP_IMS SET Usertype=?, Name=?, Gender=?, Contact=?, DOB=?, DOJ=?, Email=?, Password=?, Address=?, Salary=?, Image=? WHERE ID=?";

                try {
                    insert1 = con.prepareStatement(sql2);
                    insert1.setString(12, Luid.getText());
                    insert1.setString(1, Iusertype.getItemAt(Iusertype.getSelectedIndex()));
                    insert1.setString(2, Lname.getText());
                    insert1.setString(3, igender.getItemAt(igender.getSelectedIndex()));
                    insert1.setString(4, Lcontact.getText());
                    insert1.setString(5, ((JTextField)Ddob.getDateEditor().getUiComponent()).getText());
                    insert1.setString(6, ((JTextField)Ddoj.getDateEditor().getUiComponent()).getText());
                    insert1.setString(7, Lemail.getText());
                    insert1.setString(8, Lpass.getText());
                    insert1.setString(9, Taddress.getText());
                    insert1.setString(10, Lsalary.getText());
                    insert1.setBytes(11, photo);
                    insert1.execute();
                    javax.swing.JOptionPane.showMessageDialog(null, "Updated Successfully");
                    result();
                    clear();

                } catch (Exception ex) {
                    javax.swing.JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        clear();
    }//GEN-LAST:event_jButton6ActionPerformed

    public void clear() {
        Luid.setEditable(true);
        Luid.setText("");
        Lname.setText("");
        Lemail.setText("");
        Taddress.setText("");
        Ddob.setCalendar(null);
        Lpass.setText("");
        Lcontact.setText("");
        Ddoj.setCalendar(null);
        Lsalary.setText("");
        img_path.setText("");
        jLabel3.setIcon(null);
        Iusertype.setSelectedIndex(0);
        igender.setSelectedIndex(0);
        
    }
    
    public void result() throws SQLException {
        String sql1 = "SELECT * FROM emp_ims";
        Statement stmt = con.createStatement();
        ResultSet rs1 = stmt.executeQuery(sql1);
        DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
        tb1Model.setRowCount(0);
        
        while(rs1.next()){
            String uid1 = rs1.getString(1);
            String name1 = rs1.getString(3);
            String usertype1 = rs1.getString(2);
            String gender1 = rs1.getString(4);
            String contact1 = rs1.getString(5); 
            String dob1 = rs1.getString(6);
            String doj1 = rs1.getString(7);
            String email1 = rs1.getString(8);
            String pass1 = rs1.getString(9);
            String address1 = rs1.getString(10);
            String salary1 = rs1.getString(11);
            
            
            String tbData[] = {uid1,usertype1,name1,gender1,contact1,dob1,doj1,email1,pass1,address1,salary1};      
            tb1Model.addRow(tbData);
        }
    }
    
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
        int row = jTable1.getSelectedRow();
        Luid.setText(tb1Model.getValueAt(row, 0).toString());
        Luid.setEditable(false);
        Lname.setText(tb1Model.getValueAt(row, 2).toString());
        Lcontact.setText(tb1Model.getValueAt(row, 4).toString());
        Lemail.setText(tb1Model.getValueAt(row, 7).toString());
        Lpass.setText(tb1Model.getValueAt(row, 8).toString());
        Taddress.setText(tb1Model.getValueAt(row, 9).toString());
        Lsalary.setText(tb1Model.getValueAt(row, 10).toString());
        java.util.Date dob1;
        java.util.Date doj1;
        try {
            dob1 = new SimpleDateFormat("yyyy-MM-dd").parse((String)tb1Model.getValueAt(row, 5).toString());
            doj1 = new SimpleDateFormat("yyyy-MM-dd").parse((String)tb1Model.getValueAt(row, 6).toString());
            Ddob.setDate(dob1);
            Ddoj.setDate(doj1);
        } catch (ParseException ex) {
            Logger.getLogger(MEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            search1 = con.createStatement();
            rs = search1.executeQuery("SELECT * FROM EMP_IMS WHERE ID = '"+Luid.getText()+"'");
            rs.next();
            byte[] img = rs.getBytes(12);
            ImageIcon imm = new ImageIcon(img);
            Image im = imm.getImage();
            Image myimg = im.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon newimg = new ImageIcon(myimg);
            jLabel3.setIcon(newimg);
        }
        catch(Exception e) {

        }

        if(tb1Model.getValueAt(row, 3).equals("Male")) {
            igender.setSelectedIndex(1);
        }
        else if (tb1Model.getValueAt(row, 3).equals("Female")){
            igender.setSelectedIndex(2);
        }
        else {
            igender.setSelectedIndex(3);
        }

        if(tb1Model.getValueAt(row, 1).equals("Admin")) {
            Iusertype.setSelectedIndex(1);
        }
        else {
            Iusertype.setSelectedIndex(2);
        }

    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Ddob;
    private com.toedter.calendar.JDateChooser Ddoj;
    private javax.swing.JComboBox<String> Iusertype;
    private javax.swing.JTextField Lcontact;
    private javax.swing.JTextField Lemail;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField Lpass;
    private javax.swing.JTextField Lsalary;
    private javax.swing.JTextField Luid;
    private javax.swing.JTextArea Taddress;
    private javax.swing.JComboBox<String> igender;
    private javax.swing.JLabel img_path;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
byte[] photo = null;
String filename = null;
}

