package ims;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sanjana Shah
 */
public class MProducts extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement insert1 = null;
    Statement search1 = null;
    ResultSet rs = null;
    
    
    public MProducts() throws ClassNotFoundException, SQLException {
        initComponents();
        con = DBConnection.connectdb();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        jTable1.getTableHeader().setFont(new Font("Segoe", Font.ITALIC, 16));
        
        
        try {
            result1();
            result();
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "No record found");
        }
        
        
        
    }
    
    
    public void result1() throws SQLException {
        String sql1 = "SELECT Supplier_Name FROM Supplier_Ims";
        Statement stmt = con.createStatement();
        ResultSet rs1 = stmt.executeQuery(sql1);
        
        Csup.removeAllItems();
        Csup.addItem("Select");
        while(rs1.next()){
            String names = rs1.getString(1);      
            Csup.addItem(names);
        }
        
        String sql2 = "SELECT Category_Name FROM Cat_Ims";
        Statement stmt1 = con.createStatement();
        ResultSet rs2 = stmt1.executeQuery(sql2);
        
        Ccat.removeAllItems();
        Ccat.addItem("Select");
        while(rs2.next()){
            String names = rs2.getString(1);      
            Ccat.addItem(names);
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Lid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Csup = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Lname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Lprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Ccat = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Lqty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Cstatus = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Csearch = new javax.swing.JComboBox<>();
        Lsearch = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(252, 247, 222));
        setMaximumSize(new java.awt.Dimension(1392, 801));
        setMinimumSize(new java.awt.Dimension(1392, 801));
        setPreferredSize(new java.awt.Dimension(1392, 801));

        jPanel1.setBackground(new java.awt.Color(252, 247, 222));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel2.setText("Enter Products Details");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Product ID");

        Lid.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Lid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Supplier");

        Csup.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Csup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Product Name");

        Lname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Price");

        Lprice.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Lprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Category");

        Ccat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Ccat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Quantity");

        Lqty.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Lqty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Status");

        Cstatus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Cstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        Cstatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(55, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Csup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lid)
                                .addComponent(Lname)
                                .addComponent(Lprice)
                                .addComponent(Ccat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Lqty)
                                .addComponent(Cstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(148, 148, 148))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Csup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ccat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lqty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(252, 247, 222));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Products");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(252, 247, 222));

        jPanel4.setBackground(new java.awt.Color(252, 247, 222));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        Csearch.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Csearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search By", "Name", "Supplier", "Category", "Product ID" }));

        Lsearch.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Search");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(Csearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Lsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Csearch)
                    .addComponent(Lsearch)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(252, 247, 222));

        jScrollPane1.setBackground(new java.awt.Color(252, 247, 222));

        jTable1.setBackground(new java.awt.Color(252, 247, 222));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product_Id", "Supplier", "Name", "Price", "Category", "Quantity", "Status"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(43, 62, 79));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(Lid.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter Product ID");
        }
         else if (Csup.getSelectedIndex() == 0) {
             javax.swing.JOptionPane.showMessageDialog(null, "Please select the supplier");
         }
        else if(Lname.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter Product Name Name");
        }
        else if(Lprice.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter Product Price");
        }
        else if(Ccat.getSelectedIndex() == 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select Category");
        }
        else if(Lqty.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter Product Quamtity");
        }
        else {
            String sql1 = "INSERT INTO Product_Ims VALUES (?,?,?,?,?,?,?)";

            try {
                insert1 = con.prepareStatement(sql1);
                insert1.setString(1, Lid.getText());
                insert1.setString(2, Csup.getItemAt(Csup.getSelectedIndex()));
                insert1.setString(3, Lname.getText());
                insert1.setString(4, Lprice.getText());
                insert1.setString(5, Ccat.getItemAt(Ccat.getSelectedIndex()));
                insert1.setString(6, Lqty.getText());
                insert1.setString(7, Cstatus.getItemAt(Cstatus.getSelectedIndex()));
                insert1.execute();
                javax.swing.JOptionPane.showMessageDialog(null, "Added Successfully");
                result();
                clear();

            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clear();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
        int row = jTable1.getSelectedRow();
        Lid.setText(tb1Model.getValueAt(row, 0).toString());
        Lid.setEditable(false);
        Lname.setText(tb1Model.getValueAt(row, 2).toString());
        Lprice.setText(tb1Model.getValueAt(row, 3).toString());
        Lqty.setText(tb1Model.getValueAt(row, 5).toString());
        
        Csup.setSelectedItem(tb1Model.getValueAt(row, 1).toString());
        Ccat.setSelectedItem(tb1Model.getValueAt(row, 4).toString());
        Cstatus.setSelectedItem(tb1Model.getValueAt(row, 6).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(Lid.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please Enter Unique ID");
        }
        else {
            if (Csup.getSelectedIndex() == 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please Select Suppliet");
            }
            else if (Lname.getText().isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please enter Product Name");
            }
            else if (Lprice.getText().isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please enter Product Price ");
            }
            else if (Ccat.getSelectedIndex() == 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please select Category");
            }
            else if (Lqty.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please enter the Quantity");
            }
            else {
                String sql2 = "UPDATE Product_Ims SET supplier=?, name=?, price=?, category=?, quantity=?, status=? WHERE Product_ID=?";

                try {
                    insert1 = con.prepareStatement(sql2);
                    insert1.setString(7, Lid.getText());
                    insert1.setString(1, Csup.getItemAt(Csup.getSelectedIndex()));
                    insert1.setString(2, Lname.getText());
                    insert1.setString(3, Lprice.getText());
                    insert1.setString(4, Ccat.getItemAt(Ccat.getSelectedIndex()));
                    insert1.setString(5, Lqty.getText());
                    insert1.setString(6, Cstatus.getItemAt(Cstatus.getSelectedIndex()));
                    insert1.execute();
                    javax.swing.JOptionPane.showMessageDialog(null, "Updated Successfully");
                    result();
                    clear();

                } catch (Exception ex) {
                    javax.swing.JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(Lid.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please Enter Product ID");
        }
        else {
            String sql4 = "DELETE FROM Product_IMS WHERE Product_Id = '"+Lid.getText()+"'";

            try {
                insert1 = con.prepareStatement(sql4);
                insert1.execute();
                javax.swing.JOptionPane.showMessageDialog(null, "Deleted Successfully");
                result();
                clear();

            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(Csearch.getSelectedIndex() == 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select search by option");
        }
        else if(Csearch.getSelectedIndex() == 1) {
            String sql2 = "SELECT * FROM Product_Ims WHERE Name = '"+Lsearch.getText()+"'";

            try{
                search1 = con.createStatement();
                rs = search1.executeQuery(sql2);
                rs.next();
                Lid.setText(rs.getString(1));
                Lid.setEditable(false);
                Csup.setSelectedItem(rs.getString(2).toString());
                Lname.setText(rs.getString(3));
                Lprice.setText(rs.getString(4));
                Ccat.setSelectedItem(rs.getString(5).toString());
                Lqty.setText(rs.getString(6));
                Cstatus.setSelectedItem(rs.getString(7).toString());
            }
            catch(Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error");
            }
        }
        else if(Csearch.getSelectedIndex() == 2) {
            String sql2 = "SELECT * FROM Product_Ims WHERE Supplier = '"+Lsearch.getText()+"'";

            try{
                search1 = con.createStatement();
                rs = search1.executeQuery(sql2);
                rs.next();
                Lid.setText(rs.getString(1));
                Lid.setEditable(false);
                Csup.setSelectedItem(rs.getString(2).toString());
                Lname.setText(rs.getString(3));
                Lprice.setText(rs.getString(4));
                Ccat.setSelectedItem(rs.getString(5).toString());
                Lqty.setText(rs.getString(6));
                Cstatus.setSelectedItem(rs.getString(7).toString());
            }
            catch(Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error");
            }
        }
        else if(Csearch.getSelectedIndex() == 3) {
            String sql2 = "SELECT * FROM Product_Ims WHERE Category = '"+Lsearch.getText()+"'";

            try{
                search1 = con.createStatement();
                rs = search1.executeQuery(sql2);
                rs.next();
                Lid.setText(rs.getString(1));
                Lid.setEditable(false);
                Csup.setSelectedItem(rs.getString(2).toString());
                Lname.setText(rs.getString(3));
                Lprice.setText(rs.getString(4));
                Ccat.setSelectedItem(rs.getString(5).toString());
                Lqty.setText(rs.getString(6));
                Cstatus.setSelectedItem(rs.getString(7).toString());
            }
            catch(Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error");
            }
        }
        else if(Csearch.getSelectedIndex() == 4) {
            String sql2 = "SELECT * FROM Product_Ims WHERE Product_Id = '"+Lsearch.getText()+"'";

            try{
                search1 = con.createStatement();
                rs = search1.executeQuery(sql2);
                rs.next();
                Lid.setText(rs.getString(1));
                Lid.setEditable(false);
                Csup.setSelectedItem(rs.getString(2).toString());
                Lname.setText(rs.getString(3));
                Lprice.setText(rs.getString(4));
                Ccat.setSelectedItem(rs.getString(5).toString());
                Lqty.setText(rs.getString(6));
                Cstatus.setSelectedItem(rs.getString(7).toString());
            }
            catch(Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    
    
    public void clear() {
        Lid.setText("");
        Lid.setEditable(true);
        Lname.setText("");
        Lprice.setText("");
        Lqty.setText("");
        Csup.setSelectedIndex(0);
        Ccat.setSelectedIndex(0);
        Cstatus.setSelectedIndex(0);
        Csearch.setSelectedIndex(0);
        Lsearch.setText("");
        
    }
    
     public void result() throws SQLException {
        String sql1 = "SELECT * FROM Product_Ims";
        Statement stmt = con.createStatement();
        ResultSet rs1 = stmt.executeQuery(sql1);
        DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
        tb1Model.setRowCount(0);
        
        while(rs1.next()){
            String id1 = rs1.getString(1);
            String supp1 = rs1.getString(2);
            String name1 = rs1.getString(3);
            String price1 = rs1.getString(4);
            String cat1 = rs1.getString(5);
            String qty1 = rs1.getString(6);
            String status1 = rs1.getString(7);
            
            
            String tbData[] = {id1,supp1,name1,price1,cat1,qty1,status1};      
            tb1Model.addRow(tbData);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Ccat;
    private javax.swing.JComboBox<String> Csearch;
    private javax.swing.JComboBox<String> Cstatus;
    private javax.swing.JComboBox<String> Csup;
    private javax.swing.JTextField Lid;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField Lprice;
    private javax.swing.JTextField Lqty;
    private javax.swing.JTextField Lsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
String Data[] = {};
}
